name: SaaS Engine
on:
  schedule:
    - cron: '*/15 * * * *' # 每 15 分钟触发一次
  workflow_dispatch: # 允许在网页上手动点击运行

jobs:
  run-engine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install node-fetch@2
      
      - name: Run Script
        env:
          WORKER_URL: ${{ secrets.WORKER_URL }}
          ADMIN_PWD: ${{ secrets.ADMIN_PWD }}
        run: node engine.js
